name: musong_cafe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: 1.2.2
  qr_flutter: ^4.1.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/menu/



  fonts:
    - family: Kavoon
      fonts:
        - asset: assets/fonts/Kavoon.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/image/icon_app.png'
